In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.read_csv("spam.csv", encoding='ISO-8859-1')

In [ ]:
df.sample(5)

v1                                                 v2 Unnamed: 2  \
2391   ham                        PICK UR FONE UP NOW U DUMB?        NaN   
886    ham  I like to talk pa but am not able to. I dont k...        NaN   
962    ham  Watching cartoon, listening music &amp; at eve...        NaN   
2669  spam  we tried to contact you re your response to ou...        NaN   
2815   ham  Genius what's up. How your brother. Pls send h...        NaN   

     Unnamed: 3 Unnamed: 4  
2391        NaN        NaN  
886         NaN        NaN  
962         NaN        NaN  
2669        NaN        NaN  
2815        NaN        NaN

In [ ]:
df.shape

(5572, 5)

1.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [ ]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [ ]:
df.sample(5)

v1                                                 v2
4745  ham         Orh i tot u say she now still dun believe.
2489  ham  I have 2 docs appointments next week.:/ I'm ti...
1452  ham                  That's good, because I need drugs
136   ham                 He is there. You call and meet him
4425  ham                            Was it something u ate?

In [ ]:
df.rename(columns={'v1': 'target', 'v2': 'text'}, inplace=True)

In [ ]:
df.sample(5)

target                                               text
1213    ham  Yeah, probably but not sure. Ilol let u know, ...
4400    ham      Many times we lose our best ones bcoz we are 
3622    ham              Damn, poor zac doesn't stand a chance
5209    ham  I know you are thinkin malaria. But relax, chi...
4044    ham                      If You mean the website. Yes.

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:
df['target']=encoder.fit_transform(df['target'])

In [ ]:
df.head()

target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.isnull().sum()

target    0
text      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(403)

In [ ]:
df=df.drop_duplicates(keep='first')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(5169, 2)

2.

In [ ]:
df.head()

target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [ ]:
! pip install nltk

In [ ]:
import nltk

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
df["num_character"]=df['text'].apply(len)

In [ ]:
df.head()

target                                               text  num_character
0       0  Go until jurong point, crazy.. Available only ...            111
1       0                      Ok lar... Joking wif u oni...             29
2       1  Free entry in 2 a wkly comp to win FA Cup fina...            155
3       0  U dun say so early hor... U c already then say...             49
4       0  Nah I don't think he goes to usf, he lives aro...             61

In [ ]:
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
nltk.download('tokenizers')

[nltk_data] Error loading tokenizers: Package 'tokenizers' not found
[nltk_data]     in index


False

In [ ]:
df["num_words"] = df['text'].apply(lambda x: len(nltk.word_tokenize(x)))


In [ ]:
df.head()

target                                               text  num_character  \
0       0  Go until jurong point, crazy.. Available only ...            111   
1       0                      Ok lar... Joking wif u oni...             29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...            155   
3       0  U dun say so early hor... U c already then say...             49   
4       0  Nah I don't think he goes to usf, he lives aro...             61   

   num_words  
0         24  
1          8  
2         37  
3         13  
4         15

In [ ]:
df["num_sentences"] = df['text'].apply(lambda x: len(nltk.sent_tokenize(x)))

In [ ]:
df.head()

target                                               text  num_character  \
0       0  Go until jurong point, crazy.. Available only ...            111   
1       0                      Ok lar... Joking wif u oni...             29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...            155   
3       0  U dun say so early hor... U c already then say...             49   
4       0  Nah I don't think he goes to usf, he lives aro...             61   

   num_words  num_sentences  
0         24              2  
1          8              2  
2         37              2  
3         13              1  
4         15              1

In [ ]:
df[["num_character","num_words","num_sentences"]].describe()

num_character    num_words  num_sentences
count    5169.000000  5169.000000    5169.000000
mean       78.977945    18.455794       1.965564
std        58.236293    13.324758       1.448541
min         2.000000     1.000000       1.000000
25%        36.000000     9.000000       1.000000
50%        60.000000    15.000000       1.000000
75%       117.000000    26.000000       2.000000
max       910.000000   220.000000      38.000000

In [ ]:
df[df["target"]==0][["num_character","num_words","num_sentences"]].describe()

num_character    num_words  num_sentences
count    4516.000000  4516.000000    4516.000000
mean       70.459256    17.123782       1.820195
std        56.358207    13.493970       1.383657
min         2.000000     1.000000       1.000000
25%        34.000000     8.000000       1.000000
50%        52.000000    13.000000       1.000000
75%        90.000000    22.000000       2.000000
max       910.000000   220.000000      38.000000

In [ ]:
df[df["target"]==1][["num_character","num_words","num_sentences"]].describe()

num_character   num_words  num_sentences
count     653.000000  653.000000     653.000000
mean      137.891271   27.667688       2.970904
std        30.137753    7.008418       1.488425
min        13.000000    2.000000       1.000000
25%       132.000000   25.000000       2.000000
50%       149.000000   29.000000       3.000000
75%       157.000000   32.000000       4.000000
max       224.000000   46.000000       9.000000

3.

In [ ]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)

    y = []
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))


    return " ".join(y)

In [ ]:
from nltk.corpus import stopwords
import string
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
transform_text("I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.")

'gon na home soon want talk stuff anymor tonight k cri enough today'

In [ ]:
ps.stem('loving')

'love'

In [ ]:
df['text'][10]

"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

In [ ]:
df['transformed_text'] = df['text'].apply(transform_text)

In [ ]:
df.head()

target                                               text  num_character  \
0       0  Go until jurong point, crazy.. Available only ...            111   
1       0                      Ok lar... Joking wif u oni...             29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...            155   
3       0  U dun say so early hor... U c already then say...             49   
4       0  Nah I don't think he goes to usf, he lives aro...             61   

   num_words  num_sentences                                   transformed_text  
0         24              2  go jurong point crazi avail bugi n great world...  
1          8              2                              ok lar joke wif u oni  
2         37              2  free entri 2 wkli comp win fa cup final tkt 21...  
3         13              1                u dun say earli hor u c alreadi say  
4         15              1               nah think goe usf live around though

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer( ngram_range=(1, 2))


In [ ]:
X = tfidf.fit_transform(df['transformed_text']).toarray()


In [ ]:
X.shape


(5169, 35910)

In [ ]:
y = df['target'].values


In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)


naive


In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [ ]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [ ]:
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))


0.9197292069632496
[[832  64]
 [ 19 119]]
0.6502732240437158


In [ ]:
mnb.fit(X_train,y_train)
y_pred1 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))


0.9352030947775629
[[896   0]
 [ 67  71]]
1.0


In [ ]:
bnb.fit(X_train,y_train)
y_pred1 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))


0.9168278529980658
[[896   0]
 [ 86  52]]
1.0


LogisticRegression

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [ ]:
vec = tfidf.transform(["Congratulations! You've won a free ticket! Call now."]).toarray()
print(lr.predict(vec))
print(lr.predict_proba(vec))


[1]
[[0.35000775 0.64999225]]


smote

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE

# Balance the data
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Then split and train
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=2)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))


Accuracy: 0.9883785279468733
Precision: 0.9943820224719101
Recall: 0.9822419533851277
F1 Score: 0.9882747068676717


linearsvc

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Train LinearSVC
svc = LinearSVC()
svc.fit(X_train, y_train)

# Predict
y_pred = svc.predict(X_test)

# Evaluate
print("✅ Evaluation Metrics for LinearSVC")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))


✅ Evaluation Metrics for LinearSVC
Accuracy: 0.9983397897066962
Precision: 0.9988888888888889
Recall: 0.9977802441731409
F1 Score: 0.9983342587451416


testing

In [ ]:
def predict_spam(msg):
    msg_clean = transform_text(msg)
    print("Transformed:", msg_clean)  # Debug
    vec = tfidf.transform([msg_clean]).toarray()
    print("Vector shape:", vec.shape)  # Debug
    print("Non-zero features:", np.count_nonzero(vec))  # Debug
    return svc.predict(vec)


In [ ]:
predict_spam("You've won.")


Transformed: 
Vector shape: (1, 35910)
Non-zero features: 0


array([0])

In [ ]:
msg = "Congratulations! You've won a free ticket! Call now."
predict_spam(msg)


Transformed: congratul free ticket call
Vector shape: (1, 5000)
Non-zero features: 4


array([1])

download model

In [ ]:
import pickle

pickle.dump(svc, open('model.pkl', 'wb'))
pickle.dump(tfidf, open('vectorizer.pkl', 'wb'))
